services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: !override
      - "3030:5173"
    environment:
      - NODE_ENV=development
      - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL:-http://localhost:8090}
    depends_on:
      - pocketbase
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -lc "npm ci && npm run dev"

  pocketbase:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - VERSION=0.36.9
    ports:
      - "8090:8090"
    volumes:
      - ${DATA_PATH:-./backend/DATA}/pocketbase/pb_data:/pb_data
      - ${DATA_PATH:-./backend/DATA}/pocketbase/pb_public:/pb_public
      - ${DATA_PATH:-./backend/DATA}/pocketbase/pb_hooks:/pb_hooks
      - ${DATA_PATH:-./backend/DATA}/pocketbase/pb_migrations:/pb_migrations
