server {
  listen 3080;
  server_name edit.survey.localhost edit.survey.team-ensemble.ch;

  root /usr/share/nginx/html/editor;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}

server {
  listen 3080;
  server_name survey.localhost survey.team-ensemble.ch;

  root /usr/share/nginx/html/viewer;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}

server {
  listen 3080 default_server;
  server_name _;
  return 404;
}
